# Use the official PostgreSQL image as a parent image
FROM postgres:16.3

# Set environment variables
ENV POSTGRES_DB=dashboard_db
ENV POSTGRES_USER=diego
ENV POSTGRES_PASSWORD=psql123

# Optionally, add initialization scripts
#COPY ./init.sql /docker-entrypoint-initdb.d/

# Expose the default PostgreSQL port
EXPOSE 5432