version: '3.8'
services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./instance:/app/instance
    environment:
      - PORT=5000
      - FLASK_APP=app.py
      - NAME=World
volumes:
  instance: