services:
  db:
    image: postgres:16.3
    environment:
      POSTGRES_DB: dashboard_db
      POSTGRES_USER: diego
      POSTGRES_PASSWORD: psql123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U diego -d dashboard_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
  flask-app:
    build: 
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://diego:psql123@db:5432/dashboard_db
volumes:
  postgres_data:
