"""empty message

Revision ID: a5fa8a8ffafc
Revises: f2d627a07f8d
Create Date: 2024-06-18 10:16:58.058141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5fa8a8ffafc'
down_revision = 'f2d627a07f8d'
branch_labels = None
depends_on = None


def upgrade():
    # check and drop the _alembic_tmp_subject table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_subject")
    # drop any old data
    op.execute("delete from subject")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_subject_owner", 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subject', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
