"""add Meeting.owner_id foreign key and constraint

Revision ID: bc5f80272e3e
Revises: 7f328c1aa64c
Create Date: 2024-06-20 13:04:12.957279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc5f80272e3e'
down_revision = '7f328c1aa64c'
branch_labels = None
depends_on = None


def upgrade():
    # check and drop the _alembic_tmp_subject table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_meeting")
    # drop any old data
    op.execute("delete from meeting")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_meeting_owner", 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('meeting', schema=None) as batch_op:
        batch_op.drop_constraint("fk_meeting_owner", type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
