"""Rename user_name to username

Revision ID: bd111a2d8e06
Revises: 
Create Date: 2024-06-11 09:15:42.420487

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bd111a2d8e06"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "User",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_timestamp", sa.DateTime(), nullable=False),
        sa.Column("username", sa.String(length=16), nullable=False),
        sa.Column("password", sa.String(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.drop_table("user")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("created_timestamp", sa.DATETIME(), nullable=False),
        sa.Column("user_name", sa.VARCHAR(length=16), nullable=False),
        sa.Column("password", sa.VARCHAR(length=32), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_name"),
    )
    op.drop_table("User")
    # ### end Alembic commands ###
