"""empty message

Revision ID: e38350b8235e
Revises: 15d425e2b969
Create Date: 2024-06-20 09:57:59.743470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e38350b8235e'
down_revision = '15d425e2b969'
branch_labels = None
depends_on = None


def upgrade():
    # check and drop the _alembic_tmp_subject table if it exists
    op.execute("DROP TABLE IF EXISTS _alembic_tmp_subject")
    # drop any old data
    op.execute("delete from deliverable")

    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key("fk_deliverable_owner", 'user', ['owner_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deliverable', schema=None) as batch_op:
        batch_op.drop_constraint("fk_deliverable_owner", type_='foreignkey')
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
