"""empty message

Revision ID: f2d627a07f8d
Revises: bd111a2d8e06
Create Date: 2024-06-11 13:14:49.104404

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f2d627a07f8d"
down_revision = "bd111a2d8e06"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_login", sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column("last_logout", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("last_logout")
        batch_op.drop_column("last_login")

    # ### end Alembic commands ###
